server:
  port: 9090

spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/test_java
    username: test_java
    password: 123456
#    hikari:
#      poolName: Hikari
#      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000